import { sha256Canonical } from '../canonical-digest';
import { containsCredentialMaterial } from '../credential-guard';
import { isSecretLookingFileName } from '../secret-file-name';

/**
 * Deterministic Pull Request title and body (ADR-0108 D2/D3/D5, amends ADR-0049 CA #4/#5). Pure and
 * provider-agnostic: no I/O, no git, no config, no model call.
 *
 * - Title (D2): the approved commit's subject (`committedSubject`, recorded on the anchor when the approved commit
 *   ran). Absent or refused → `chore: update <first path> (+N files)`. The instruction text is never the title.
 * - Body (D3): the approved commit (short hash + subject), head → base, the workspace-relative paths of the committed
 *   files (≤ {@link MAX_PR_BODY_LISTED_FILES}, then "+N more") and "Generated by Quoky; not merged". Never file
 *   content, diffs or secret-looking names. ≤ {@link MAX_PR_BODY_CHARS} characters.
 * - Binding (D5): {@link prDescriptionContentHash} is the SHA-256 of (title, body) stored with the CRITICAL PR approval;
 *   the execution re-hashes the stored text and creates no PR on a mismatch.
 *
 * The optional model-proposed title/body (D4, `QUOKY_PR_DESCRIPTION_MODEL_ENABLED`, default `false`) is not wired:
 * with the flag off the deterministic text is the only text, which is the release default.
 */

/** Maximum PR title (and committed subject) length in characters (ADR-0108 D2). */
export const MAX_PR_TITLE_CHARS = 72;
/** Maximum PR body length in characters (ADR-0108 D3). */
export const MAX_PR_BODY_CHARS = 4000;
/** Committed file paths listed in the body before "+N more" (ADR-0108 D3). */
export const MAX_PR_BODY_LISTED_FILES = 20;
/** Longest single path listed in the body; a longer path is counted in "+N more" instead. */
const MAX_PR_BODY_PATH_CHARS = 200;
/** Longest branch name shown in the body. */
const MAX_PR_BODY_BRANCH_CHARS = 80;
/** The fixed provenance line (ADR-0108 D3). */
export const PR_BODY_PROVENANCE_LINE = 'Generated by Quoky; not merged.';
/** Domain separator of the (title, body) binding hash. */
const PR_DESCRIPTION_HASH_DOMAIN = 'quoky.pr-description.v1';

/** The exact title and body a PR approval covers, with their binding hash. */
export interface PrDescription {
  readonly title: string;
  readonly body: string;
  /** SHA-256 of (title, body) — {@link prDescriptionContentHash}. */
  readonly contentHash: string;
}

/** What the deterministic description is built from — all of it already on the approved anchor. */
export interface PrDescriptionInput {
  /** The approved commit's subject, if recorded (see {@link committedSubjectOf}). */
  readonly committedSubject?: string;
  /** The pushed (approved) commit hash. */
  readonly commitHash: string;
  /** Workspace-relative paths of the committed files. */
  readonly committedFiles: readonly string[];
  readonly headBranch: string;
  readonly baseBranch: string;
}

// eslint-disable-next-line no-control-regex
const CONTROL_CHARS = /[\u0000-\u001f\u007f]/;
// eslint-disable-next-line no-control-regex
const CONTROL_CHARS_GLOBAL = /[\u0000-\u001f\u007f]/g;

/** Truncate to `max` code points, ending in "…" when shortened. */
function boundChars(text: string, max: number): string {
  const chars = Array.from(text);
  return chars.length <= max ? text : `${chars.slice(0, max - 1).join('')}…`;
}

/**
 * The PR-title subject of an approved commit message (ADR-0108 D2): its first line, control characters removed,
 * whitespace collapsed, at most {@link MAX_PR_TITLE_CHARS} characters. `undefined` when empty or when it carries
 * credential material (refused; the title then falls back to the file-based form).
 */
export function committedSubjectOf(message: string | undefined): string | undefined {
  if (typeof message !== 'string') return undefined;
  const firstLine = message.split(/\r?\n/, 1)[0] ?? '';
  const cleaned = firstLine.replace(CONTROL_CHARS_GLOBAL, ' ').replace(/\s+/g, ' ').trim();
  if (cleaned.length === 0 || containsCredentialMaterial(cleaned)) return undefined;
  return boundChars(cleaned, MAX_PR_TITLE_CHARS);
}

/**
 * A committed path that may appear in the title or body: relative, no `..`, no control characters or backticks,
 * bounded, not secret-looking by name (ADR-0019/0022 — such files cannot be committed; this is defence in depth) and
 * carrying no credential material. Anything else is never shown, only counted.
 */
function isListablePath(path: string): boolean {
  if (typeof path !== 'string') return false;
  const p = path.trim();
  if (p.length === 0 || p.length > MAX_PR_BODY_PATH_CHARS) return false;
  if (CONTROL_CHARS.test(p) || p.includes('`')) return false;
  if (/^([a-zA-Z]:[\\/]|[\\/])/.test(p)) return false;
  if (p.split(/[\\/]/).includes('..')) return false;
  const base = p.split(/[\\/]/).pop() ?? p;
  if (isSecretLookingFileName(base)) return false;
  return !containsCredentialMaterial(p);
}

/** A bounded single-line branch name for the body. */
function bodyBranch(branch: string): string {
  return boundChars(branch.replace(CONTROL_CHARS_GLOBAL, '').trim(), MAX_PR_BODY_BRANCH_CHARS);
}

/**
 * The deterministic title (ADR-0108 D2): the committed subject, else `chore: update <first path> (+N files)` over
 * the listable committed paths, bounded to {@link MAX_PR_TITLE_CHARS} (the path shortens first, so the count stays).
 */
export function deterministicPrTitle(committedSubject: string | undefined, committedFiles: readonly string[]): string {
  const subject = committedSubjectOf(committedSubject);
  if (subject) return subject;
  const listable = committedFiles.filter(isListablePath).map((p) => p.trim());
  const first = listable[0];
  if (!first) {
    const n = committedFiles.length;
    return n > 0 ? `chore: update ${n} ${n === 1 ? 'file' : 'files'}` : 'chore: update approved changes';
  }
  const others = committedFiles.length - 1;
  const prefix = 'chore: update ';
  const suffix = others > 0 ? ` (+${others} ${others === 1 ? 'file' : 'files'})` : '';
  const room = MAX_PR_TITLE_CHARS - Array.from(prefix).length - Array.from(suffix).length;
  return `${prefix}${boundChars(first, room)}${suffix}`;
}

/** The deterministic body (ADR-0108 D3), at most {@link MAX_PR_BODY_CHARS} characters. */
export function deterministicPrBody(input: PrDescriptionInput): string {
  const subject = committedSubjectOf(input.committedSubject);
  const shortHash = input.commitHash.slice(0, 7);
  const files = input.committedFiles;
  const listable = files.filter(isListablePath).map((p) => p.trim());
  let listed = listable.slice(0, MAX_PR_BODY_LISTED_FILES);
  const render = (shown: readonly string[]): string => {
    const more = files.length - shown.length;
    return [
      PR_BODY_PROVENANCE_LINE,
      '',
      `Commit: \`${shortHash}\`${subject ? ` ${subject}` : ''}`,
      `Branch: ${bodyBranch(input.headBranch)} → ${bodyBranch(input.baseBranch)}`,
      '',
      `Changed files (${files.length}):`,
      ...shown.map((p) => `- \`${p}\``),
      ...(more > 0 ? [`- +${more} more`] : []),
    ].join('\n');
  };
  let body = render(listed);
  while (body.length > MAX_PR_BODY_CHARS && listed.length > 0) {
    listed = listed.slice(0, -1);
    body = render(listed);
  }
  return body.length > MAX_PR_BODY_CHARS ? body.slice(0, MAX_PR_BODY_CHARS) : body;
}

/** SHA-256 binding of the exact (title, body) pair a CRITICAL PR approval covers (ADR-0108 D5). */
export function prDescriptionContentHash(title: string, body: string): string {
  return sha256Canonical(PR_DESCRIPTION_HASH_DOMAIN, { title, body });
}

/** The deterministic PR description with its binding hash (ADR-0108 D2/D3/D5). */
export function buildDeterministicPrDescription(input: PrDescriptionInput): PrDescription {
  const title = deterministicPrTitle(input.committedSubject, input.committedFiles);
  const body = deterministicPrBody(input);
  return { title, body, contentHash: prDescriptionContentHash(title, body) };
}
